apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ex-dns-admin
  namespace: jx-resources
spec:
  member: serviceAccount:${CLUSTER_NAME?}-ex@${PROJECT_ID?}.iam.gserviceaccount.com
  role: roles/dns.admin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${PROJECT_ID?}