apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: tk-viewer
  namespace: jx-resources
spec:
  member: serviceAccount:${CLUSTER_NAME?}-tk@${PROJECT_ID?}.iam.gserviceaccount.com
  role: roles/viewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${PROJECT_ID?}